import { renderStaffShell, bindStaffShell } from '../components/staff-shell.js';
import { showModal, showToast } from '../components/ui.js';
import { clearTeacherAuthenticated, createClass, createUser, deleteUser, downloadFullSchoolBackup, getAllClasses, getAllUsers, getAuditLog, restoreFullSchoolBackup, ROLE_LABELS, USER_ROLES, updateClass, updateUser } from '../engine/storage.js';

const escapeHTML = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');

export async function renderAdministration() {
  const [users, classes, audit] = await Promise.all([getAllUsers(), getAllClasses(), getAuditLog()]);
  const staffRows = users.map((user) => `<div class="admin-list__item staff-page-row" data-staff-search="${escapeHTML(`${user.name || ''} ${user.username} ${ROLE_LABELS[user.role] || ''}`.toLowerCase())}"><div><strong>${escapeHTML(user.name || user.username)}</strong><span>${escapeHTML(ROLE_LABELS[user.role] || user.role)} · @${escapeHTML(user.username)}</span></div><button class="btn btn--ghost btn--xs" data-open-staff-modal>Manage</button></div>`).join('');
  const content = `<div class="workspace-card-grid"><button class="workspace-action-card" id="admin-staff"><strong>Staff accounts</strong><span>${users.length} staff account${users.length === 1 ? '' : 's'} · roles and class assignments</span></button><button class="workspace-action-card" id="admin-classes"><strong>School classes</strong><span>${classes.length} class${classes.length === 1 ? '' : 'es'} · academic structure</span></button><button class="workspace-action-card" id="admin-backup"><strong>Backups</strong><span>Download a full school data backup</span></button><button class="workspace-action-card" id="admin-audit"><strong>Audit log</strong><span>${audit.length} accountable system events</span></button></div><section class="card dashboard-panel"><h2 class="chart-card__title">Staff management</h2><p class="chart-card__subtitle">Search staff accounts, then manage access, roles, PINs, and class assignments.</p><input id="staff-page-search" class="input input--sm" placeholder="Search staff by name, username, or role"><div class="admin-list" id="staff-page-list">${staffRows}</div><div class="export-area"><button class="btn btn--secondary" id="admin-staff-secondary">Add or manage staff</button><button class="btn btn--secondary" id="admin-classes-secondary">Manage classes</button><button class="btn btn--ghost" id="admin-audit-secondary">View audit log</button><button class="btn btn--ghost" id="admin-restore">Restore backup</button><input type="file" id="admin-restore-file" accept="application/json,.json" hidden></div></section>`;
  return renderStaffShell({ title: 'Administration', subtitle: 'Staff access, school setup, records accountability, and data protection.', activePath: '/admin', content });
}

export function bindAdministrationEvents(navigate) {
  bindStaffShell(navigate, { onLogout: () => { clearTeacherAuthenticated(); navigate('/'); } });
  ['admin-staff', 'admin-staff-secondary'].forEach((id) => document.getElementById(id)?.addEventListener('click', () => void openStaffModal(navigate)));
  document.querySelectorAll('[data-open-staff-modal]').forEach((button) => button.addEventListener('click', () => void openStaffModal(navigate)));
  document.getElementById('staff-page-search')?.addEventListener('input', (event) => { const query = event.currentTarget.value.trim().toLowerCase(); document.querySelectorAll('.staff-page-row').forEach((row) => { row.hidden = !!query && !row.dataset.staffSearch.includes(query); }); });
  ['admin-classes', 'admin-classes-secondary'].forEach((id) => document.getElementById(id)?.addEventListener('click', () => void openClassesModal(navigate)));
  ['admin-audit', 'admin-audit-secondary'].forEach((id) => document.getElementById(id)?.addEventListener('click', () => void openAuditModal()));
  document.getElementById('admin-backup')?.addEventListener('click', async () => { await downloadFullSchoolBackup(); showToast('Full school backup downloaded.', 'success'); });
  document.getElementById('admin-restore')?.addEventListener('click', () => document.getElementById('admin-restore-file')?.click());
  document.getElementById('admin-restore-file')?.addEventListener('change', (event) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = async () => { try { if (!confirm('Restore this backup? Existing records will be merged.')) return; await restoreFullSchoolBackup(JSON.parse(reader.result), 'merge'); showToast('School backup restored.', 'success'); navigate('/admin', false); } catch (error) { showToast(error.message || 'Could not restore this backup.', 'error'); } }; reader.readAsText(file); });
}

async function openStaffModal(navigate) {
  const [users, classes] = await Promise.all([getAllUsers(), getAllClasses()]);
  const html = `<div class="admin-list">${users.map((user) => `<div class="admin-list__item"><div><strong>${escapeHTML(user.name || user.username)}</strong><span>${escapeHTML(ROLE_LABELS[user.role] || user.role)} · @${escapeHTML(user.username)}</span></div><div><button class="btn btn--ghost btn--xs" data-edit-user="${user.id}">Edit</button>${user.role !== USER_ROLES.ADMIN ? `<button class="btn btn--ghost btn--xs" data-remove-user="${user.id}">Deactivate</button>` : ''}</div></div>`).join('')}</div><form id="admin-create-staff" class="admin-form"><h3>Add staff account</h3><input class="input" id="new-staff-name" required placeholder="Full name"><input class="input" id="new-staff-username" required pattern="[A-Za-z0-9._-]{3,40}" placeholder="Username"><input class="input input--pin" id="new-staff-pin" required pattern="[0-9]{4,8}" maxlength="8" inputmode="numeric" placeholder="4–8 digit PIN"><select class="input" id="new-staff-role">${Object.entries(ROLE_LABELS).map(([role, label]) => `<option value="${role}">${escapeHTML(label)}</option>`).join('')}</select><label>Assigned classes<select class="input" id="new-staff-classes" multiple>${classes.map((entry) => `<option value="${entry.id}">${escapeHTML(entry.name)}</option>`).join('')}</select></label><button class="btn btn--primary">Create account</button></form>`;
  showModal('Staff accounts', html, [{ label: 'Close', variant: 'btn--ghost' }], { modalClass: 'modal--wide' });
  document.getElementById('admin-create-staff')?.addEventListener('submit', async (event) => { event.preventDefault(); try { await createUser({ name: document.getElementById('new-staff-name').value.trim(), username: document.getElementById('new-staff-username').value.trim(), pin: document.getElementById('new-staff-pin').value.trim(), role: document.getElementById('new-staff-role').value, classIds: [...document.getElementById('new-staff-classes').selectedOptions].map((item) => Number(item.value)) }); showToast('Staff account created.', 'success'); document.querySelector('.modal-backdrop')?.remove(); navigate('/admin', false); } catch (error) { showToast(error.message, 'error'); } });
  document.querySelectorAll('[data-remove-user]').forEach((button) => button.addEventListener('click', async () => { if (!confirm('Deactivate this staff account?')) return; await deleteUser(Number(button.dataset.removeUser)); showToast('Staff account deactivated.', 'success'); document.querySelector('.modal-backdrop')?.remove(); navigate('/admin', false); }));
  document.querySelectorAll('[data-edit-user]').forEach((button) => button.addEventListener('click', () => openEditStaffModal(users.find((user) => user.id === Number(button.dataset.editUser)), classes, navigate)));
}

function openEditStaffModal(user, classes, navigate) { if (!user) return; const html = `<form id="admin-edit-staff" class="admin-form" style="margin-top:0;border-top:0"><input class="input" id="edit-staff-name" value="${escapeHTML(user.name || '')}" required><select class="input" id="edit-staff-role">${Object.entries(ROLE_LABELS).map(([role, label]) => `<option value="${role}" ${user.role === role ? 'selected' : ''}>${escapeHTML(label)}</option>`).join('')}</select><label>Assigned classes<select class="input" id="edit-staff-classes" multiple>${classes.map((entry) => `<option value="${entry.id}" ${(user.classIds || []).includes(entry.id) ? 'selected' : ''}>${escapeHTML(entry.name)}</option>`).join('')}</select></label><input class="input input--pin" id="edit-staff-pin" pattern="[0-9]{4,8}" maxlength="8" inputmode="numeric" placeholder="New PIN (leave blank to keep current)"><button class="btn btn--primary">Save changes</button></form>`; showModal(`Edit ${user.name || user.username}`, html, [{ label: 'Cancel', variant: 'btn--ghost' }]); document.getElementById('admin-edit-staff')?.addEventListener('submit', async (event) => { event.preventDefault(); const role = document.getElementById('edit-staff-role').value; if (role !== user.role && !confirm(`Change ${user.name || user.username}'s role? This changes what they can access.`)) return; const pin = document.getElementById('edit-staff-pin').value.trim(); await updateUser(user.id, { name: document.getElementById('edit-staff-name').value.trim(), role, classIds: [...document.getElementById('edit-staff-classes').selectedOptions].map((item) => Number(item.value)), ...(pin ? { pin } : {}) }); showToast('Staff account updated.', 'success'); document.querySelector('.modal-backdrop')?.remove(); navigate('/admin', false); }); }

async function openClassesModal(navigate) {
  const classes = await getAllClasses();
  const html = `<div class="admin-list">${classes.map((entry) => `<div class="admin-list__item"><div><strong>${escapeHTML(entry.name)}</strong><span>${escapeHTML(entry.academicYear || '')} · ${escapeHTML(entry.term || '')} · ${escapeHTML(entry.teacherName || 'No class teacher')}</span></div></div>`).join('')}</div><form id="admin-create-class" class="admin-form"><h3>Create class</h3><input class="input" id="new-class-name" required placeholder="e.g., B7 — JHS 1A"><input class="input" id="new-class-year" value="2026/2027" placeholder="Academic year"><select class="input" id="new-class-term"><option>Term 1</option><option>Term 2</option><option>Term 3</option></select><input class="input" id="new-class-teacher" placeholder="Class teacher"><button class="btn btn--primary">Create class</button></form>`;
  showModal('School classes', html, [{ label: 'Close', variant: 'btn--ghost' }], { modalClass: 'modal--wide' });
  document.getElementById('admin-create-class')?.addEventListener('submit', async (event) => { event.preventDefault(); await createClass({ name: document.getElementById('new-class-name').value.trim(), academicYear: document.getElementById('new-class-year').value.trim(), term: document.getElementById('new-class-term').value, teacherName: document.getElementById('new-class-teacher').value.trim() }); showToast('Class created.', 'success'); document.querySelector('.modal-backdrop')?.remove(); navigate('/admin', false); });
}

async function openAuditModal() {
  const entries = await getAuditLog();
  const renderEntries = (items) => items.map((entry) => `<div class="admin-list__item"><div><strong>${escapeHTML(entry.action)}</strong><span>${new Date(entry.createdAt).toLocaleString()} · Actor: ${escapeHTML(entry.actor || 'system')} · Record: ${escapeHTML(Object.values(entry.detail || {}).join(' · ') || 'System')}</span></div></div>`).join('') || '<p class="insight-empty">No audit events match these filters.</p>';
  const html = `<div class="audit-filters"><input class="input input--sm" id="audit-search" placeholder="Search actor, action, or record"><input class="input input--sm" id="audit-date" type="date"><select class="input input--sm" id="audit-action"><option value="">All actions</option>${[...new Set(entries.map((entry) => entry.action))].map((action) => `<option>${escapeHTML(action)}</option>`).join('')}</select></div><div class="admin-list" id="audit-list">${renderEntries(entries)}</div>`;
  showModal('System audit log', html, [{ label: 'Close', variant: 'btn--ghost' }], { modalClass: 'modal--wide' });
  const apply = () => { const query = document.getElementById('audit-search').value.trim().toLowerCase(); const date = document.getElementById('audit-date').value; const action = document.getElementById('audit-action').value; document.getElementById('audit-list').innerHTML = renderEntries(entries.filter((entry) => (!query || `${entry.actor} ${entry.action} ${JSON.stringify(entry.detail)}`.toLowerCase().includes(query)) && (!date || entry.createdAt.startsWith(date)) && (!action || entry.action === action))); };
  ['audit-search', 'audit-date', 'audit-action'].forEach((id) => document.getElementById(id)?.addEventListener(id === 'audit-search' ? 'input' : 'change', apply));
}
